# Generated by Django 4.1 on 2024-05-11 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validation_on_edge", models.BooleanField()),
                ("can_be_used", models.BooleanField()),
                ("ip", models.GenericIPAddressField()),
                (
                    "device_name",
                    models.TextField(default="Unknown Device", max_length=30),
                ),
                ("data_path", models.FilePathField()),
                ("edge_working_directory", models.FilePathField()),
                ("edge_ram_gb", models.FloatField(blank=True)),
                ("edge_storage_gb", models.FloatField(blank=True)),
                (
                    "model_output_dest",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="api.device",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.TextField(default="Unknown Model", max_length=20),
                ),
                (
                    "model_path",
                    models.FileField(upload_to="", verbose_name="/aggregated_models/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Run_History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.device"
                    ),
                ),
                (
                    "run_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.run"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Model_History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.device"
                    ),
                ),
                (
                    "model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.model"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "error_file",
                    models.FileField(
                        blank=True, upload_to="", verbose_name="/error_log_files/"
                    ),
                ),
                (
                    "device_log_file",
                    models.FileField(upload_to="", verbose_name="/device_log_files/"),
                ),
                (
                    "model_log_file",
                    models.FileField(upload_to="", verbose_name="/model_log_files/"),
                ),
                (
                    "model_upload",
                    models.FileField(
                        upload_to="",
                        verbose_name="/client_model_after_training_before_agg/",
                    ),
                ),
                (
                    "device_end",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.device"
                    ),
                ),
                (
                    "initial_model_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.model"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.run"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Device_Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_device",
                        to="api.device",
                        verbose_name="Current Device",
                    ),
                ),
                (
                    "next_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_device",
                        to="api.device",
                        verbose_name="Next Device",
                    ),
                ),
            ],
        ),
    ]
